import { Staff } from "./types";

export const initialStaff: Staff[] = [
  {
    id: "s1",
    name: "Hoàng An Nam",
    gender: "Nam",
    birthday: "1990-05-12",
    email: "annam@center.vn",
    phone: "0901234567",
    introduce: "Huấn luyện viên Pickleball với 5 năm kinh nghiệm thi đấu và giảng dạy.",
    status: "active",
    systemRole: "Coach Full",
    centerRole: "HLV chính",
    subjects: ["Pickleball", "Tennis"],
    startDate: "2020-12-20",
    experienceYears: 5,
    achievements: ["HCV Pickleball mở rộng 2023", "Top 10 Tennis miền Nam 2021"],
    expertises: [
      { id: "e1", subject: "Pickleball", years: 5, note: "Chuyên dạy kỹ thuật cơ bản và chiến thuật thi đấu đôi." },
      { id: "e2", subject: "Tennis", years: 3, note: "Huấn luyện kỹ thuật cơ bản cho người mới." },
    ],
    classesCount: 3,
    certificates: [
      { id: "c1", name: "Chứng chỉ Huấn luyện Pickleball Level 1", issuedBy: "VPA", issuedYear: 2023, expiredYear: 2026, subject: "Pickleball" },
      { id: "c2", name: "Chứng chỉ HLV Tennis cơ bản", issuedBy: "VTF", issuedYear: 2021, expiredYear: null, subject: "Tennis" },
    ],
  },
  {
    id: "s2",
    name: "Thầy Trung",
    gender: "Nam",
    birthday: "1985-03-08",
    email: "trung@center.vn",
    phone: "0907654321",
    introduce: "Giảng viên bóng chuyền lâu năm.",
    status: "active",
    systemRole: "Coach Full",
    centerRole: "Giảng viên",
    subjects: ["Bóng chuyền"],
    startDate: "2019-06-15",
    experienceYears: 8,
    achievements: ["HCB giải bóng chuyền tỉnh"],
    expertises: [
      { id: "e3", subject: "Bóng chuyền", years: 8, note: "Huấn luyện thi đấu cho học sinh - sinh viên." },
    ],
    classesCount: 2,
    certificates: [
      { id: "c3", name: "HLV Bóng chuyền cấp 2", issuedBy: "VFV", issuedYear: 2018, expiredYear: null, subject: "Bóng chuyền" },
    ],
  },
  {
    id: "s3",
    name: "Nguyễn Minh Anh",
    gender: "Nữ",
    birthday: "1995-09-20",
    email: "minhanh@center.vn",
    phone: "0912345678",
    introduce: "Nhân viên hành chính, hỗ trợ vận hành.",
    status: "active",
    systemRole: "Staff",
    centerRole: "Nhân viên hỗ trợ",
    subjects: [],
    startDate: "2024-01-10",
    experienceYears: 1,
    achievements: [],
    expertises: [],
    classesCount: 0,
    certificates: [],
  },
  {
    id: "s4",
    name: "Lê Thanh Tú",
    gender: "Nam",
    birthday: "1992-11-02",
    email: "thanhtu@center.vn",
    phone: "0934567890",
    introduce: "HLV Pickleball trẻ nhiều tiềm năng.",
    status: "inactive",
    systemRole: "Coach",
    centerRole: "Trợ giảng",
    subjects: ["Pickleball"],
    startDate: "2022-03-05",
    endDate: "2025-12-31",
    experienceYears: 3,
    achievements: ["HCĐ Pickleball trẻ 2022"],
    expertises: [],
    classesCount: 1,
    certificates: [
      { id: "c4", name: "Pickleball Coach Level 1", issuedBy: "VPA", issuedYear: 2022, expiredYear: 2025, subject: "Pickleball" },
      { id: "c5", name: "First Aid", issuedBy: "Hội Chữ Thập Đỏ", issuedYear: 2023, expiredYear: 2026 },
      { id: "c6", name: "Fitness Trainer", issuedBy: "ACE", issuedYear: 2021, expiredYear: null },
    ],
  },
  {
    id: "s5",
    name: "Trần Gia Hân",
    gender: "Nữ",
    birthday: "1988-07-14",
    email: "giahan@center.vn",
    phone: "0945678901",
    introduce: "Quản trị viên hệ thống và HLV Tennis.",
    status: "active",
    systemRole: "Admin",
    centerRole: "Quản lý",
    subjects: ["Tennis"],
    startDate: "2018-09-01",
    experienceYears: 7,
    achievements: ["HCV Tennis nữ miền Nam"],
    expertises: [],
    classesCount: 0,
    certificates: [
      { id: "c7", name: "HLV Tennis Level 2", issuedBy: "VTF", issuedYear: 2020, expiredYear: 2026, subject: "Tennis" },
      { id: "c8", name: "Quản lý CLB thể thao", issuedBy: "TDTT", issuedYear: 2019, expiredYear: null },
    ],
  },
  {
    id: "s6",
    name: "Phạm Quốc Khánh",
    gender: "Nam",
    birthday: "1993-02-18",
    email: "khanh@center.vn",
    phone: "0956789012",
    introduce: "HLV Cầu lông kinh nghiệm.",
    status: "active",
    systemRole: "Coach",
    centerRole: "Giảng viên",
    subjects: ["Cầu lông"],
    startDate: "2021-05-12",
    experienceYears: 4,
    achievements: ["HCB Cầu lông tỉnh 2022"],
    expertises: [],
    classesCount: 2,
    certificates: [
      { id: "c9", name: "HLV Cầu lông", issuedBy: "VBF", issuedYear: 2020, expiredYear: 2026, subject: "Cầu lông" },
    ],
  },
  {
    id: "s7",
    name: "Đặng Thu Hà",
    gender: "Nữ",
    birthday: "1996-12-01",
    email: "thuha@center.vn",
    phone: "0967890123",
    introduce: "Trợ giảng Pickleball.",
    status: "active",
    systemRole: "Coach",
    centerRole: "Trợ giảng",
    subjects: ["Pickleball"],
    startDate: "2024-08-01",
    experienceYears: 1,
    achievements: [],
    expertises: [],
    classesCount: 1,
    certificates: [],
  },
  {
    id: "s8",
    name: "Vũ Đức Long",
    gender: "Nam",
    birthday: "1987-04-25",
    email: "duclong@center.vn",
    phone: "0978901234",
    introduce: "Chủ sở hữu trung tâm và HLV Tennis lâu năm.",
    status: "active",
    systemRole: "Owner",
    centerRole: "Quản lý",
    subjects: ["Tennis", "Pickleball"],
    startDate: "2015-01-01",
    experienceYears: 12,
    achievements: ["Sáng lập trung tâm", "HCV Tennis quốc gia 2010"],
    expertises: [],
    classesCount: 0,
    certificates: [
      { id: "c10", name: "HLV Tennis Quốc gia", issuedBy: "VTF", issuedYear: 2010, expiredYear: null, subject: "Tennis" },
    ],
  },
  {
    id: "s9",
    name: "Bùi Khánh Linh",
    gender: "Nữ",
    birthday: "1998-08-08",
    email: "khanhlinh@center.vn",
    phone: "0989012345",
    introduce: "Nhân viên lễ tân và hỗ trợ học viên.",
    status: "inactive",
    systemRole: "Staff",
    centerRole: "Nhân viên hỗ trợ",
    subjects: [],
    startDate: "2023-11-20",
    experienceYears: 1,
    achievements: [],
    expertises: [],
    classesCount: 0,
    certificates: [],
  },
];
